//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectToMidi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectToMidi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add block.
        /// </summary>
        public static string AddBlock {
            get {
                return ResourceManager.GetString("AddBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC:.
        /// </summary>
        public static string CCColon {
            get {
                return ResourceManager.GetString("CCColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel:.
        /// </summary>
        public static string ChannelColon {
            get {
                return ResourceManager.GetString("ChannelColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions:.
        /// </summary>
        public static string ConditionsColon {
            get {
                return ResourceManager.GetString("ConditionsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occured:.
        /// </summary>
        public static string ErrorOccuredColon {
            get {
                return ResourceManager.GetString("ErrorOccuredColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type:.
        /// </summary>
        public static string EventTypeColon {
            get {
                return ResourceManager.GetString("EventTypeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error was occured. See &apos;{0}&apos; for more details..
        /// </summary>
        public static string FatalErrorMessage {
            get {
                return ResourceManager.GetString("FatalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First joint:.
        /// </summary>
        public static string FirstJointColon {
            get {
                return ResourceManager.GetString("FirstJointColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightColon {
            get {
                return ResourceManager.GetString("HeightColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint:.
        /// </summary>
        public static string JointColon {
            get {
                return ResourceManager.GetString("JointColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string LengthColon {
            get {
                return ResourceManager.GetString("LengthColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max:.
        /// </summary>
        public static string MaxColon {
            get {
                return ResourceManager.GetString("MaxColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC midi signal.
        /// </summary>
        public static string MidiCC {
            get {
                return ResourceManager.GetString("MidiCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi:.
        /// </summary>
        public static string MidiColon {
            get {
                return ResourceManager.GetString("MidiColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured on opening specified MIDI port.
        /// </summary>
        public static string MidiErrorText {
            get {
                return ResourceManager.GetString("MidiErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note midi signal.
        /// </summary>
        public static string MidiNote {
            get {
                return ResourceManager.GetString("MidiNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midi settings:.
        /// </summary>
        public static string MidiSettingsColon {
            get {
                return ResourceManager.GetString("MidiSettingsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        public static string MinColon {
            get {
                return ResourceManager.GetString("MinColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string NoteColon {
            get {
                return ResourceManager.GetString("NoteColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note state:.
        /// </summary>
        public static string NoteStateColon {
            get {
                return ResourceManager.GetString("NoteStateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string OnIn {
            get {
                return ResourceManager.GetString("OnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        public static string OnOut {
            get {
                return ResourceManager.GetString("OnOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over.
        /// </summary>
        public static string OnOver {
            get {
                return ResourceManager.GetString("OnOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius:.
        /// </summary>
        public static string RadiusColon {
            get {
                return ResourceManager.GetString("RadiusColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second joint:.
        /// </summary>
        public static string SecondJointColon {
            get {
                return ResourceManager.GetString("SecondJointColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Kinect stream in separate window.
        /// </summary>
        public static string ShowKinectWindowTitle {
            get {
                return ResourceManager.GetString("ShowKinectWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Skeleton map.
        /// </summary>
        public static string SkeletonMap {
            get {
                return ResourceManager.GetString("SkeletonMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton point to coordinate.
        /// </summary>
        public static string SkeletonPointToCordinate {
            get {
                return ResourceManager.GetString("SkeletonPointToCordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton point to skeleton point.
        /// </summary>
        public static string SkeletonPointToSkeletonPoint {
            get {
                return ResourceManager.GetString("SkeletonPointToSkeletonPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity:.
        /// </summary>
        public static string VelocityColon {
            get {
                return ResourceManager.GetString("VelocityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video....
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load project.
        /// </summary>
        public static string WarningMessage_CannotLoadProject {
            get {
                return ResourceManager.GetString("WarningMessage_CannotLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string WidthColon {
            get {
                return ResourceManager.GetString("WidthColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string XColon {
            get {
                return ResourceManager.GetString("XColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string YColon {
            get {
                return ResourceManager.GetString("YColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z:.
        /// </summary>
        public static string ZColon {
            get {
                return ResourceManager.GetString("ZColon", resourceCulture);
            }
        }
    }
}
